
SEND_MAX = 10 # 10

SEND_INTERVAL = 10 # seconds

#
SEND_OK = 0
SEND_NOT_ALLOW_BECAUSE_AMOUNT = 1
SEND_NOT_ALLOW_BECAUSE_INTERVAL = 2
SEND_NOT_ALLOW_BECAUSE_TOKEN_ATTEMPTS = 3

SEND_NOT_ALLOW_BECAUSE_IP_BLOCKED = 4
