
SEND_MAX = 20

SEND_INTERVAL = 10 # seconds

#
SEND_OK = 0
SEND_NOT_ALLOW_BECAUSE_AMOUNT = 1
SEND_NOT_ALLOW_BECAUSE_INTERVAL = 2
SEND_NOT_ALLOW_BECAUSE_TOKEN_ATTEMPTS = 3

SEND_NOT_ALLOW_BECAUSE_IP_BLOCKED = 4

## UserEmailCode
VALIDITY = 60*30 # half hour

FIELD_UNDEFINED = 0
FIELD_LOGIN = 1
FIELD_SIGN = 2

FIELD_ABLE = [ FIELD_UNDEFINED, FIELD_SIGN, FIELD_LOGIN]
